---
- hosts: ansible_host
  tasks:
  - name: build docker image with war file
    command: docker image build -t java-hello-world .
    args:
      chdir: /home/vagrant/hello-world
  - name: run container using java-hello-world image
    command: docker run -d --name java-hello-world-container -p 8080:8080 java-hello-world
